import assert from "node:assert/strict";
import test from "node:test";
import { joinDeliveryEvidence, validateDeliveryEvidenceSnapshot } from "../scripts/lib/delivery-evidence-joiner.mjs";
import { buildkite, fixture, plane, provider, releases } from "./helpers/delivery-evidence-fixture.mjs";
test("delivery join requires explicit Plane key and exact commit evidence",()=>{const x=joinDeliveryEvidence({providerSnapshot:provider(),planeSnapshot:plane(),buildkiteSnapshots:[buildkite()],releaseSnapshot:releases()});const r=x.deliveryRecords[0];assert.deepEqual(r.plane,{status:"linked",key:"INTB-260",stateGroup:"started",updatedAt:fixture.at});assert.equal(r.ci.status,"passed");assert.equal(r.release.status,"shipped");assert.equal(r.deployment.status,"unavailable");});
test("delivery snapshot retains exact portable source observations",()=>{const x=joinDeliveryEvidence({providerSnapshot:provider(),planeSnapshot:plane(),buildkiteSnapshots:[buildkite()],releaseSnapshot:releases()});assert.deepEqual(x.sources.plane.observations.map((item)=>item.id),["plane:intelip"]);assert.match(x.sources.plane.observations[0].digest,/^[0-9a-f]{64}$/);assert.deepEqual(x.sources.buildkite.observations.map((item)=>item.id),["buildkite:intelip/tabellio"]);assert.deepEqual(x.sources.githubRelease.observations.map((item)=>item.id),["github-release:IntelIP/Tabellio"]);});
test("release shipping remains true without deployment proof",()=>{const x=joinDeliveryEvidence({providerSnapshot:provider(),planeSnapshot:plane(),buildkiteSnapshots:[buildkite()],releaseSnapshot:releases()});assert.equal(x.deliveryRecords[0].release.status,"shipped");assert.equal(x.deliveryRecords[0].deployment.status,"unavailable");});
test("delivery join rejects cross-repository CI and deployment evidence",()=>{const ci=buildkite();ci.repository="IntelIP/Other";assert.throws(()=>joinDeliveryEvidence({providerSnapshot:provider(),planeSnapshot:plane(),buildkiteSnapshots:[ci],releaseSnapshot:releases()}),/Buildkite snapshot repository mismatch/);const receipt={schemaVersion:"tabellio-deployment-receipt/v0.1",id:"deploy-1",repository:"IntelIP/Other",environment:"production",commit:"a".repeat(40),status:"passed",deployedAt:fixture.at,observedAt:fixture.at,provider:"cloud-run",externalId:"rev-1"};const x=joinDeliveryEvidence({providerSnapshot:provider(),planeSnapshot:plane(),buildkiteSnapshots:[buildkite()],releaseSnapshot:releases(),deploymentReceipts:[receipt]});assert.equal(x.deliveryRecords[0].deployment.status,"unavailable");});
test("delivery snapshot rejects bare successful status claims",()=>{const x=joinDeliveryEvidence({providerSnapshot:provider(),planeSnapshot:plane(),buildkiteSnapshots:[buildkite()],releaseSnapshot:releases()});x.deliveryRecords[0].ci={status:"passed",pipeline:null,buildNumber:null,finishedAt:null};assert.throws(()=>validateDeliveryEvidenceSnapshot(x),/Passed CI evidence requires/);});
